add_test( [==[Register union test]==] /home/ahmed/Repos/gbemu/bin/my_tests [==[Register union test]==]  )
set_tests_properties( [==[Register union test]==] PROPERTIES WORKING_DIRECTORY /home/ahmed/Repos/gbemu/tests)
add_test( [==[CPUFlags union test]==] /home/ahmed/Repos/gbemu/bin/my_tests [==[CPUFlags union test]==]  )
set_tests_properties( [==[CPUFlags union test]==] PROPERTIES WORKING_DIRECTORY /home/ahmed/Repos/gbemu/tests)
add_test( [==[ROM loading test]==] /home/ahmed/Repos/gbemu/bin/my_tests [==[ROM loading test]==]  )
set_tests_properties( [==[ROM loading test]==] PROPERTIES WORKING_DIRECTORY /home/ahmed/Repos/gbemu/tests)
add_test( [==[CPU get_r16_from_opcode test]==] /home/ahmed/Repos/gbemu/bin/my_tests [==[CPU get_r16_from_opcode test]==]  )
set_tests_properties( [==[CPU get_r16_from_opcode test]==] PROPERTIES WORKING_DIRECTORY /home/ahmed/Repos/gbemu/tests)
add_test( [==[CPU get_r8_from_opcode test]==] /home/ahmed/Repos/gbemu/bin/my_tests [==[CPU get_r8_from_opcode test]==]  )
set_tests_properties( [==[CPU get_r8_from_opcode test]==] PROPERTIES WORKING_DIRECTORY /home/ahmed/Repos/gbemu/tests)
add_test( [==[CPU add and sub test]==] /home/ahmed/Repos/gbemu/bin/my_tests [==[CPU add and sub test]==]  )
set_tests_properties( [==[CPU add and sub test]==] PROPERTIES WORKING_DIRECTORY /home/ahmed/Repos/gbemu/tests)
add_test( [==[CPU step test]==] /home/ahmed/Repos/gbemu/bin/my_tests [==[CPU step test]==]  )
set_tests_properties( [==[CPU step test]==] PROPERTIES WORKING_DIRECTORY /home/ahmed/Repos/gbemu/tests)
set( my_tests_TESTS [==[Register union test]==] [==[CPUFlags union test]==] [==[ROM loading test]==] [==[CPU get_r16_from_opcode test]==] [==[CPU get_r8_from_opcode test]==] [==[CPU add and sub test]==] [==[CPU step test]==])
